name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      drink:
        description: 'order drink'
        required: true
      food:
        description: 'order food'
        required: false

jobs:
  order:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "tnx ${{ github.event.inputs.drink }}!"
        echo "- in ${{ github.event.inputs.food }}!"
